print "Raj: Hi, My name is Rajendra and i am from India"
print "Alex: What about you?"
print "Raj: My name is Alex and i am from Washington DC"
print "Alex: How are you doing?"
print "Raj: Great, day starts with coding and feeling so much passionate about it"
print "Raj: What about you?"
print "Alex: Me too, I do code for 12 hours everyday"
print "Raj: Wow, that's wonderful and lot of coding"
print "Raj: It's nice to meet you and see you in class" 
print "Alex: Yeah, see you when i see you"